FROM node:24-alpine AS base
WORKDIR /frontend
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN npm install -g pnpm

FROM base AS dependencies
COPY package.json .
RUN --mount=type=cache,mode=0755,id=pnpm,target=/pnpm/store pnpm install
#RUN pnpm install

FROM dependencies AS build
# copy over initial code (further changes will be synced by 'docker compose watch')
COPY . .

WORKDIR /frontend

RUN pnpm build