services:
  frontend-dist:
    build:
      context: ./frontend
      dockerfile: dockerfile-prod
    ports:
      - "8001:8001"
  backend-prod:
    build:
      context: ./backend
      dockerfile: dockerfile-prod
    depends_on:
      - frontend-dist
    ports:
      - "8000:8000"
    restart: unless-stopped