services:
  frontend:
    build:
      context: ./frontend
      dockerfile: dockerfile
    ports:
      - "8001:8001"
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: ./frontend
          target: /frontend
          initial_sync: true
          ignore:
            - /frontend/node_modules/
        - action: rebuild
          path: ./frontend/package.json
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - "./data:/mnt"
    develop:
      watch:
        - action: sync
          path: ./backend
          target: ./backend
          initial_sync: true
          ignore:
            - ".venv"
        - action: rebuild
          path: ./backend/pyproject.toml