FROM astral/uv:debian-slim AS base
WORKDIR /backend

ENV UV_LINK_MODE=copy

COPY pyproject.toml .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-install-project
RUN uv run playwright install chromium --with-deps

COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync

FROM base AS runtime

CMD ["uv", "run", "fastapi", "dev", "main.py", "--host", "0.0.0.0"]