FROM astral/uv:alpine
WORKDIR /backend

ENV UV_LINK_MODE=copy

COPY pyproject.toml .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync --no-install-project

COPY . .
RUN --mount=type=cache,target=/root/.cache/uv \
    uv sync

COPY --from=aomc-map-frontend-dist /frontend/dist /data/frontend

CMD ["uv", "run", "fastapi", "run", "main.py", "--host", "0.0.0.0"]